package markdown

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"time"

	"github.com/arran4/golang-ical"
	"gopkg.in/yaml.v3"
)

// isGeneratedTitle checks if a title appears to be generated by the calendar system
func isGeneratedTitle(title interface{}) bool {
	if titleStr, ok := title.(string); ok {
		// Check if it matches common generated title patterns
		if titleStr == "Events (Date TBD)" {
			return true
		}
		// Check if it matches the weekday, month day, year format we generate
		if _, err := time.Parse("Monday, January 2, 2006", titleStr); err == nil {
			return true
		}
	}
	return false
}

// parseICalDateTime attempts to parse an iCalendar date/time string in various formats
func parseICalDateTime(value string) (time.Time, bool, error) {
	return parseICalDateTimeWithTZ(value, "")
}

// parseICalDateTimeWithTZ attempts to parse an iCalendar date/time string with optional time zone
// If timezone is specified, converts to local time. If no timezone is specified, assumes local time.
func parseICalDateTimeWithTZ(value, tzid string) (time.Time, bool, error) {
	if strings.HasPrefix(value, "0001") {
		return time.Time{}, false, nil
	}

	// Remove any whitespace
	value = strings.TrimSpace(value)
	tzid = strings.TrimSpace(tzid)

	// Try UTC format with Z suffix first - convert to local time
	if strings.HasSuffix(value, "Z") {
		if t, err := time.Parse("20060102T150405Z", value); err == nil {
			return t.In(time.Local), false, nil // Convert UTC to local time
		}
		// Try with fractional seconds
		if t, err := time.Parse("20060102T150405.000Z", value); err == nil {
			return t.In(time.Local), false, nil // Convert UTC to local time
		}
	}

	// Handle local time with TZID - convert to local time
	if tzid != "" {
		// Try parsing with time component
		if t, err := time.Parse("20060102T150405", value); err == nil {
			// Try to load the time zone using our enhanced mapping
			if loc := mapTimeZone(tzid); loc != nil {
				// Parse the time in the specified time zone
				sourceTime := time.Date(t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), loc)
				// Convert to local time
				return sourceTime.In(time.Local), false, nil
			}
			// If timezone cannot be resolved, treat as local time and warn
			return t, false, fmt.Errorf("unrecognized timezone '%s', treating as local time", tzid)
		}

		// Try with fractional seconds
		if t, err := time.Parse("20060102T150405.000", value); err == nil {
			if loc := mapTimeZone(tzid); loc != nil {
				sourceTime := time.Date(t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), loc)
				return sourceTime.In(time.Local), false, nil
			}
			return t, false, fmt.Errorf("unrecognized timezone '%s', treating as local time", tzid)
		}
	}

	// Try local time format without Z suffix and without TZID - assume local time
	if t, err := time.Parse("20060102T150405", value); err == nil {
		// No TZID provided, interpret as local time by reconstructing in local timezone
		localTime := time.Date(t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), time.Local)
		return localTime, false, nil
	}

	// Try with fractional seconds
	if t, err := time.Parse("20060102T150405.000", value); err == nil {
		// No TZID provided, interpret as local time by reconstructing in local timezone
		localTime := time.Date(t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), time.Local)
		return localTime, false, nil
	}

	// Try date-only format - always local
	if t, err := time.Parse("20060102", value); err == nil {
		// Ensure date is in local time
		localTime := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.Local)
		return localTime, true, nil // true indicates all-day
	}

	// Try date with dashes (less common but valid)
	if t, err := time.Parse("2006-01-02", value); err == nil {
		// Ensure date is in local time
		localTime := time.Date(t.Year(), t.Month(), t.Day(), 0, 0, 0, 0, time.Local)
		return localTime, true, nil
	}

	// Try datetime with dashes and colons - assume local
	if t, err := time.Parse("2006-01-02T15:04:05", value); err == nil {
		// No timezone specified, interpret as local time
		localTime := time.Date(t.Year(), t.Month(), t.Day(), t.Hour(), t.Minute(), t.Second(), t.Nanosecond(), time.Local)
		return localTime, false, nil
	}

	// Try datetime with dashes, colons, and timezone - convert to local
	if t, err := time.Parse("2006-01-02T15:04:05Z", value); err == nil {
		return t.In(time.Local), false, nil // Convert UTC to local time
	}

	return time.Time{}, false, fmt.Errorf("could not parse date/time: %s (tzid: %s)", value, tzid)
}

// mapTimeZone provides common time zone ID mappings for CalDAV/iCalendar compatibility
func mapTimeZone(tzid string) *time.Location {
	// Handle empty timezone
	if tzid == "" {
		return nil
	}

	// Try loading the timezone directly first (for IANA standard names)
	if loc, err := time.LoadLocation(tzid); err == nil {
		return loc
	}

	// Common mappings for Microsoft Exchange and other systems
	commonMappings := map[string]string{
		// Microsoft Exchange Standard Time Names
		"Eastern Standard Time":                "America/New_York",
		"Eastern Daylight Time":               "America/New_York",
		"Central Standard Time":               "America/Chicago",
		"Central Daylight Time":               "America/Chicago",
		"Mountain Standard Time":              "America/Denver",
		"Mountain Daylight Time":              "America/Denver",
		"Pacific Standard Time":               "America/Los_Angeles",
		"Pacific Daylight Time":               "America/Los_Angeles",
		"GMT Standard Time":                   "Europe/London",
		"Greenwich Standard Time":             "Europe/London",
		"W. Europe Standard Time":             "Europe/Berlin",
		"Central European Standard Time":      "Europe/Berlin",
		"Central European Summer Time":        "Europe/Berlin",
		"E. Europe Standard Time":             "Europe/Bucharest",
		"Tokyo Standard Time":                 "Asia/Tokyo",
		"China Standard Time":                 "Asia/Shanghai",
		"India Standard Time":                 "Asia/Kolkata",
		"AUS Eastern Standard Time":           "Australia/Sydney",
		"Australian Eastern Standard Time":    "Australia/Sydney",
		"AUS Central Standard Time":           "Australia/Adelaide",
		"AUS Western Standard Time":           "Australia/Perth",
		// Common abbreviations
		"EST":                                 "America/New_York",
		"EDT":                                 "America/New_York",
		"CST":                                 "America/Chicago",
		"CDT":                                 "America/Chicago",
		"MST":                                 "America/Denver",
		"MDT":                                 "America/Denver",
		"PST":                                 "America/Los_Angeles",
		"PDT":                                 "America/Los_Angeles",
		"UTC":                                 "UTC",
		"GMT":                                 "UTC",
		"CET":                                 "Europe/Berlin",
		"CEST":                                "Europe/Berlin",
		"JST":                                 "Asia/Tokyo",
		"AEST":                                "Australia/Sydney",
		"AEDT":                                "Australia/Sydney",
		// Additional common formats
		"(UTC-05:00) Eastern Time (US & Canada)": "America/New_York",
		"(UTC-06:00) Central Time (US & Canada)": "America/Chicago",
		"(UTC-07:00) Mountain Time (US & Canada)": "America/Denver",
		"(UTC-08:00) Pacific Time (US & Canada)": "America/Los_Angeles",
		"(UTC+00:00) Dublin, Edinburgh, Lisbon, London": "Europe/London",
		"(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna": "Europe/Berlin",
		"(UTC+09:00) Osaka, Sapporo, Tokyo": "Asia/Tokyo",
	}

	if iana, exists := commonMappings[tzid]; exists {
		if loc, err := time.LoadLocation(iana); err == nil {
			return loc
		}
	}

	// Try common timezone name variations
	variations := []string{
		// Remove common suffixes
		strings.ReplaceAll(tzid, " Standard Time", ""),
		strings.ReplaceAll(tzid, " Daylight Time", ""),
		strings.ReplaceAll(tzid, " Summer Time", ""),
		// Replace spaces with underscores (common variation)
		strings.ReplaceAll(tzid, " ", "_"),
	}

	for _, variation := range variations {
		if variation != tzid && variation != "" {
			if loc, err := time.LoadLocation(variation); err == nil {
				return loc
			}
		}
	}

	return nil
}

type EventMarkdown struct {
	Title       string
	Description string
	Location    string
	StartTime   time.Time
	EndTime     time.Time
	AllDay      bool
	UID         string
	Status      string
	Categories  []string
	Calendar    string // Display name (alias if available, otherwise original name)
	CalendarOriginal string // Original calendar name for hashtag generation
}

// IsPastEvent determines if an event has already occurred
func (em EventMarkdown) IsPastEvent() bool {
	now := time.Now()

	// If no start time, can't determine if it's past
	if em.StartTime.IsZero() {
		return false
	}

	// For all-day events, compare with the date only
	if em.AllDay {
		eventDate := em.StartTime.Truncate(24 * time.Hour)
		currentDate := now.Truncate(24 * time.Hour)
		return eventDate.Before(currentDate)
	}

	// For timed events, use end time if available, otherwise start time
	compareTime := em.StartTime
	if !em.EndTime.IsZero() {
		compareTime = em.EndTime
	}

	return compareTime.Before(now)
}

type TodoMarkdown struct {
	Title       string
	Description string
	Status      string
	Priority    string
	DueDate     time.Time
	Completed   bool
	UID         string
	Categories  []string
	Calendar    string // Display name (alias if available, otherwise original name)
	CalendarOriginal string // Original calendar name for hashtag generation
}

// ConvertEventWithCalendar converts an event with calendar name and alias information
func ConvertEventWithCalendar(event *ics.VEvent, calendarName string, calendarAliases map[string]string) EventMarkdown {
	md := ConvertEvent(event)

	// Use provided calendar name or fall back to extracted name
	finalCalendarName := calendarName
	if finalCalendarName == "" {
		finalCalendarName = md.Calendar
	}

	// Store original calendar name for hashtag generation
	md.CalendarOriginal = finalCalendarName

	// Set display calendar name, using alias if available
	if finalCalendarName != "" {
		if alias, exists := calendarAliases[finalCalendarName]; exists {
			md.Calendar = alias
		} else {
			md.Calendar = finalCalendarName
		}
	}

	return md
}

func ConvertEvent(event *ics.VEvent) EventMarkdown {
	var md EventMarkdown

	if summary := event.GetProperty(ics.ComponentPropertySummary); summary != nil {
		md.Title = summary.Value
	}

	if description := event.GetProperty(ics.ComponentPropertyDescription); description != nil {
		md.Description = description.Value
	}

	if location := event.GetProperty(ics.ComponentPropertyLocation); location != nil {
		md.Location = location.Value
	}

	if uid := event.GetProperty(ics.ComponentPropertyUniqueId); uid != nil {
		md.UID = uid.Value
	}

	if status := event.GetProperty(ics.ComponentPropertyStatus); status != nil {
		md.Status = status.Value
	}

	// Parse categories
	if categories := event.GetProperty(ics.ComponentPropertyCategories); categories != nil {
		md.Categories = strings.Split(categories.Value, ",")
		for i, cat := range md.Categories {
			md.Categories[i] = strings.TrimSpace(cat)
		}
	}

	// Try to extract calendar name from common properties
	if calNameProp := event.GetProperty("X-WR-CALNAME"); calNameProp != nil {
		md.Calendar = calNameProp.Value
	} else if prodIdProp := event.GetProperty("PRODID"); prodIdProp != nil {
		// Extract calendar name from PRODID if it contains recognizable patterns
		prodId := prodIdProp.Value
		if strings.Contains(prodId, "Google") {
			md.Calendar = "Google Calendar"
		}
	}

	if dtstart := event.GetProperty(ics.ComponentPropertyDtStart); dtstart != nil {
		// Extract TZID parameter if present
		var tzid string
		if tzids, exists := dtstart.ICalParameters["TZID"]; exists && len(tzids) > 0 {
			tzid = tzids[0]
		}

		if startTime, allDay, err := parseICalDateTimeWithTZ(dtstart.Value, tzid); err == nil {
			md.StartTime = startTime
			if allDay {
				md.AllDay = true
			}
		}
	}

	if dtend := event.GetProperty(ics.ComponentPropertyDtEnd); dtend != nil {
		// Extract TZID parameter if present
		var tzid string
		if tzids, exists := dtend.ICalParameters["TZID"]; exists && len(tzids) > 0 {
			tzid = tzids[0]
		}

		if endTime, allDay, err := parseICalDateTimeWithTZ(dtend.Value, tzid); err == nil {
			md.EndTime = endTime
			if allDay {
				md.AllDay = true
			}
		}
	}

	// Ensure all events have both start and end times
	if !md.StartTime.IsZero() && md.EndTime.IsZero() {
		// If no end time is specified, set default duration based on event type
		if md.AllDay {
			// For all-day events, end at the end of the same day
			md.EndTime = md.StartTime.Add(24 * time.Hour).Add(-1 * time.Second)
		} else {
			// For timed events, default to 1 hour duration if no DURATION property
			defaultDuration := time.Hour

			// Check for DURATION property
			if duration := event.GetProperty(ics.ComponentPropertyDuration); duration != nil {
				if parsedDuration, err := parseICalDuration(duration.Value); err == nil {
					defaultDuration = parsedDuration
				}
			}

			md.EndTime = md.StartTime.Add(defaultDuration)
		}
	}

	return md
}

func (em EventMarkdown) ToMarkdown() string {
	return em.ToMarkdownWithOptions(false)
}

func (em EventMarkdown) ToMarkdownWithOptions(ignoreDescriptions bool) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# %s\n\n", em.Title))

	// Handle events with zero time (0001-01-01)
	if em.StartTime.IsZero() && em.EndTime.IsZero() {
		sb.WriteString("**Date:** No date specified\n\n")
	} else if em.StartTime.IsZero() {
		sb.WriteString(fmt.Sprintf("**End:** %s\n\n", em.EndTime.Format("2006-01-02 15:04")))
	} else if em.EndTime.IsZero() {
		if em.AllDay {
			sb.WriteString(fmt.Sprintf("**Date:** %s (All Day)\n\n", em.StartTime.Format("2006-01-02")))
		} else {
			sb.WriteString(fmt.Sprintf("**Start:** %s\n\n", em.StartTime.Format("2006-01-02 15:04")))
		}
	} else if em.AllDay {
		// For all-day events, show the date range
		if em.StartTime.Format("2006-01-02") == em.EndTime.Format("2006-01-02") {
			sb.WriteString(fmt.Sprintf("**Date:** %s (All Day)\n\n", em.StartTime.Format("2006-01-02")))
		} else {
			sb.WriteString(fmt.Sprintf("**Date:** %s to %s (All Day)\n\n",
				em.StartTime.Format("2006-01-02"),
				em.EndTime.Format("2006-01-02")))
		}
	} else {
		// For timed events, always show both start and end times
		sb.WriteString(fmt.Sprintf("**Start:** %s\n", em.StartTime.Format("2006-01-02 15:04")))
		sb.WriteString(fmt.Sprintf("**End:** %s\n", em.EndTime.Format("2006-01-02 15:04")))

		// Calculate and show duration
		duration := em.EndTime.Sub(em.StartTime)
		sb.WriteString(fmt.Sprintf("**Duration:** %s\n", formatDuration(duration)))
		sb.WriteString("\n")
	}

	if em.Location != "" {
		sb.WriteString(fmt.Sprintf("**Location:** %s\n\n", em.Location))
	}

	if !ignoreDescriptions && em.Description != "" {
		sb.WriteString("## Description\n\n")
		sb.WriteString(em.Description)
		sb.WriteString("\n\n")
	}

	return sb.String()
}

// ToListItem returns a compact markdown list format for daily aggregation
func (em EventMarkdown) ToListItem() string {
	return em.ToListItemWithOptions(false, false, false)
}

// ToListItemWithOptions returns a compact markdown list format with optional hashtags, descriptions, and checkboxes
func (em EventMarkdown) ToListItemWithOptions(useHashtags, ignoreDescriptions, useCheckboxes bool) string {
	return em.ToListItemWithOptionsAndCalendarTags(useHashtags, ignoreDescriptions, useCheckboxes, false)
}

// ToListItemWithOptionsAndCalendarTags returns a compact markdown list format with full option control
func (em EventMarkdown) ToListItemWithOptionsAndCalendarTags(useHashtags, ignoreDescriptions, useCheckboxes, useCalendarTags bool) string {
	return em.ToListItemWithAllOptions(useHashtags, ignoreDescriptions, useCheckboxes, useCalendarTags, false)
}

// ToListItemWithAllOptions returns a compact markdown list format with complete option control including Obsidian Tasks emojis
func (em EventMarkdown) ToListItemWithAllOptions(useHashtags, ignoreDescriptions, useCheckboxes, useCalendarTags, useObsidianEmojis bool) string {
	var sb strings.Builder

	// Add UID as HTML comment for deduplication and updates
	if em.UID != "" {
		sb.WriteString(fmt.Sprintf("<!-- uid:%s -->\n", em.UID))
	}

	// Choose prefix based on checkbox option and whether event is in the past
	prefix := "-"
	if useCheckboxes {
		if em.IsPastEvent() {
			prefix = "- [x]" // Mark past events as completed
		} else {
			prefix = "- [ ]" // Future events remain unchecked
		}
	}

	if em.AllDay {
		sb.WriteString(fmt.Sprintf("%s **%s** (All Day)", prefix, em.Title))
	} else if em.StartTime.IsZero() {
		sb.WriteString(fmt.Sprintf("%s **%s** (Time TBD)", prefix, em.Title))
	} else {
		if useObsidianEmojis {
			// Use Obsidian Tasks emoji format for timed events
			startDate := em.StartTime.Format("2006-01-02")
			startTime := em.StartTime.Format("15:04")
			if em.EndTime.IsZero() || em.EndTime.Equal(em.StartTime) {
				sb.WriteString(fmt.Sprintf("%s **%s** 🛫 %s %s", prefix, em.Title, startDate, startTime))
			} else {
				endDate := em.EndTime.Format("2006-01-02")
				endTime := em.EndTime.Format("15:04")
				// Use start emoji for start time and done emoji for end time
				if startDate == endDate {
					// Same day - show both times with emojis
					sb.WriteString(fmt.Sprintf("%s **%s** 🛫 %s %s ✅ %s", prefix, em.Title, startDate, startTime, endTime))
				} else {
					// Different days - show full date/time for both
					sb.WriteString(fmt.Sprintf("%s **%s** 🛫 %s %s ✅ %s %s", prefix, em.Title, startDate, startTime, endDate, endTime))
				}
			}
		} else {
			// Original format without Obsidian emojis
			startTime := em.StartTime.Format("15:04")
			if em.EndTime.IsZero() || em.EndTime.Equal(em.StartTime) {
				sb.WriteString(fmt.Sprintf("%s **%s** at %s", prefix, em.Title, startTime))
			} else {
				endTime := em.EndTime.Format("15:04")
				sb.WriteString(fmt.Sprintf("%s **%s** (%s - %s)", prefix, em.Title, startTime, endTime))
			}
		}
	}

	if em.Location != "" {
		sb.WriteString(fmt.Sprintf(" @ %s", em.Location))
	}

	if em.Calendar != "" {
		sb.WriteString(fmt.Sprintf(" [%s]", em.Calendar))
	}

	// Collect hashtags and deduplicate them
	var hashtags []string

	if useHashtags {
		hashtags = append(hashtags, "#event")
	}

	if useCalendarTags && em.CalendarOriginal != "" {
		calendarTag := sanitizeForHashtag(em.CalendarOriginal)
		if calendarTag != "" {
			hashtags = append(hashtags, "#"+calendarTag)
		}
	}

	// Deduplicate and add hashtags
	hashtags = deduplicateHashtags(hashtags)
	if len(hashtags) > 0 {
		sb.WriteString(" " + strings.Join(hashtags, " "))
	}

	if !ignoreDescriptions && em.Description != "" {
		// Add description on a new line with indentation
		sb.WriteString(fmt.Sprintf("\n  %s", strings.ReplaceAll(em.Description, "\n", "\n  ")))
	}

	sb.WriteString("\n")
	return sb.String()
}

func (em EventMarkdown) Filename() string {
	safeTitle := strings.ReplaceAll(em.Title, "/", "-")
	safeTitle = strings.ReplaceAll(safeTitle, "\\", "-")
	safeTitle = strings.ReplaceAll(safeTitle, ":", "-")
	safeTitle = strings.ReplaceAll(safeTitle, "*", "-")
	safeTitle = strings.ReplaceAll(safeTitle, "?", "-")
	safeTitle = strings.ReplaceAll(safeTitle, "\"", "-")
	safeTitle = strings.ReplaceAll(safeTitle, "<", "-")
	safeTitle = strings.ReplaceAll(safeTitle, ">", "-")
	safeTitle = strings.ReplaceAll(safeTitle, "|", "-")

	var dateStr string
	if em.StartTime.IsZero() {
		dateStr = "0001-01-01"
	} else {
		dateStr = em.StartTime.Format("2006-01-02")
	}
	return fmt.Sprintf("%s_%s.md", dateStr, safeTitle)
}

func GenerateFilename(outputDir string, event EventMarkdown) string {
	// Create YYYY/MM directory structure
	var year, month string
	if event.StartTime.IsZero() {
		year = "0001"
		month = "01"
	} else {
		year = event.StartTime.Format("2006")
		month = event.StartTime.Format("01")
	}
	yearMonthDir := filepath.Join(outputDir, year, month)

	return filepath.Join(yearMonthDir, event.Filename())
}

func EnsureDirectoryExists(filePath string) error {
	dir := filepath.Dir(filePath)
	return os.MkdirAll(dir, 0755)
}

// ConvertTodoWithCalendar converts a todo with calendar name and alias information
func ConvertTodoWithCalendar(todo *ics.VTodo, calendarName string, calendarAliases map[string]string) TodoMarkdown {
	md := ConvertTodo(todo)

	// Use provided calendar name or fall back to extracted name
	finalCalendarName := calendarName
	if finalCalendarName == "" {
		finalCalendarName = md.Calendar
	}

	// Store original calendar name for hashtag generation
	md.CalendarOriginal = finalCalendarName

	// Set display calendar name, using alias if available
	if finalCalendarName != "" {
		if alias, exists := calendarAliases[finalCalendarName]; exists {
			md.Calendar = alias
		} else {
			md.Calendar = finalCalendarName
		}
	}

	return md
}

func ConvertTodo(todo *ics.VTodo) TodoMarkdown {
	var md TodoMarkdown

	if summary := todo.GetProperty(ics.ComponentPropertySummary); summary != nil {
		md.Title = summary.Value
	}

	if description := todo.GetProperty(ics.ComponentPropertyDescription); description != nil {
		md.Description = description.Value
	}

	if status := todo.GetProperty(ics.ComponentPropertyStatus); status != nil {
		md.Status = status.Value
		md.Completed = status.Value == "COMPLETED"
	}

	if priority := todo.GetProperty(ics.ComponentPropertyPriority); priority != nil {
		md.Priority = priority.Value
	}

	if due := todo.GetProperty(ics.ComponentPropertyDue); due != nil {
		// Extract TZID parameter if present
		var tzid string
		if tzids, exists := due.ICalParameters["TZID"]; exists && len(tzids) > 0 {
			tzid = tzids[0]
		}

		if dueTime, _, err := parseICalDateTimeWithTZ(due.Value, tzid); err == nil {
			md.DueDate = dueTime
		}
	}

	if uid := todo.GetProperty(ics.ComponentPropertyUniqueId); uid != nil {
		md.UID = uid.Value
	}

	// Parse categories
	if categories := todo.GetProperty(ics.ComponentPropertyCategories); categories != nil {
		md.Categories = strings.Split(categories.Value, ",")
		for i, cat := range md.Categories {
			md.Categories[i] = strings.TrimSpace(cat)
		}
	}

	// Try to extract calendar name from common properties
	if calNameProp := todo.GetProperty("X-WR-CALNAME"); calNameProp != nil {
		md.Calendar = calNameProp.Value
	} else if prodIdProp := todo.GetProperty("PRODID"); prodIdProp != nil {
		// Extract calendar name from PRODID if it contains recognizable patterns
		prodId := prodIdProp.Value
		if strings.Contains(prodId, "Google") {
			md.Calendar = "Google Calendar"
		}
	}

	return md
}

func (tm TodoMarkdown) ToMarkdown() string {
	return tm.ToMarkdownWithOptions(false, false, false)
}

func (tm TodoMarkdown) ToMarkdownWithOptions(useDueDateEmoji, useHashtags, ignoreDescriptions bool) string {
	return tm.ToMarkdownWithOptionsAndCalendarTags(useDueDateEmoji, useHashtags, ignoreDescriptions, false)
}

// ToMarkdownWithOptionsAndCalendarTags returns task markdown with full option control
func (tm TodoMarkdown) ToMarkdownWithOptionsAndCalendarTags(useDueDateEmoji, useHashtags, ignoreDescriptions, useCalendarTags bool) string {
	var sb strings.Builder

	// Add UID as HTML comment for deduplication and updates
	if tm.UID != "" {
		sb.WriteString(fmt.Sprintf("<!-- uid:%s -->\n", tm.UID))
	}

	checkbox := "- [ ]"
	if tm.Completed {
		checkbox = "- [x]"
	}

	sb.WriteString(fmt.Sprintf("%s **%s**", checkbox, tm.Title))

	if tm.Priority != "" && tm.Priority != "0" {
		sb.WriteString(fmt.Sprintf(" (Priority: %s)", tm.Priority))
	}

	if !tm.DueDate.IsZero() {
		if useDueDateEmoji {
			sb.WriteString(fmt.Sprintf(" - 📅 %s", tm.DueDate.Format("2006-01-02")))
		} else {
			sb.WriteString(fmt.Sprintf(" - Due: %s", tm.DueDate.Format("2006-01-02")))
		}
	}

	if tm.Status != "" {
		sb.WriteString(fmt.Sprintf(" - Status: %s", tm.Status))
	}

	if tm.Calendar != "" {
		sb.WriteString(fmt.Sprintf(" [%s]", tm.Calendar))
	}

	// Collect hashtags and deduplicate them
	var hashtags []string

	if useHashtags {
		hashtags = append(hashtags, "#task")
	}

	if useCalendarTags && tm.CalendarOriginal != "" {
		calendarTag := sanitizeForHashtag(tm.CalendarOriginal)
		if calendarTag != "" {
			hashtags = append(hashtags, "#"+calendarTag)
		}
	}

	// Deduplicate and add hashtags
	hashtags = deduplicateHashtags(hashtags)
	if len(hashtags) > 0 {
		sb.WriteString(" " + strings.Join(hashtags, " "))
	}

	sb.WriteString("\n")

	if !ignoreDescriptions && tm.Description != "" {
		sb.WriteString(fmt.Sprintf("  %s\n", tm.Description))
	}

	sb.WriteString("\n")
	return sb.String()
}

func GenerateTasksFile(outputDir string, todos []TodoMarkdown) error {
	var sb strings.Builder
	sb.WriteString("# Tasks\n\n")

	for _, todo := range todos {
		sb.WriteString(todo.ToMarkdown())
	}

	tasksPath := filepath.Join(outputDir, "tasks.md")
	return writeToFile(tasksPath, sb.String())
}

// GenerateTodoFile creates a todo.md file for tasks without due dates with smart merging
func GenerateTodoFile(outputDir string, todos []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, useCalendarTags bool, progressCallback ProgressCallback) error {
	if progressCallback != nil {
		progressCallback(fmt.Sprintf("Generating todo.md with %d tasks", len(todos)), 0, 1)
	}

	todoPath := filepath.Join(outputDir, "todo.md")

	// Parse existing todo.md file if it exists
	existingContent, err := parseExistingTodoFile(todoPath)
	if err != nil {
		return fmt.Errorf("failed to parse existing todo.md file: %v", err)
	}

	// Convert tasks to markdown strings
	var newTasks []string
	for _, task := range todos {
		newTasks = append(newTasks, strings.TrimSpace(task.ToMarkdownWithOptionsAndCalendarTags(useDueDateEmoji, useHashtags, ignoreDescriptions, useCalendarTags)))
	}

	// Generate merged content
	content := generateMergedTodoContent(existingContent, newTasks, todos, useFrontmatter, useHashtags, useCalendarTags)

	// Write to file
	if err := writeToFile(todoPath, content); err != nil {
		return fmt.Errorf("failed to write todo.md file: %v", err)
	}

	if progressCallback != nil {
		progressCallback("Generated todo.md", 1, 1)
	}

	return nil
}

func writeToFile(filename, content string) error {
	file, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer file.Close()

	_, err = file.WriteString(content)
	return err
}

// parseICalDuration parses an iCalendar DURATION value (RFC 5545)
// Format: ["+"|"-"] "P" [n "W"] [n "D"] ["T" [n "H"] [n "M"] [n "S"]]
func parseICalDuration(durationStr string) (time.Duration, error) {
	// Remove optional leading + or -
	sign := 1
	if strings.HasPrefix(durationStr, "-") {
		sign = -1
		durationStr = durationStr[1:]
	} else if strings.HasPrefix(durationStr, "+") {
		durationStr = durationStr[1:]
	}

	// Must start with P
	if !strings.HasPrefix(durationStr, "P") {
		return 0, fmt.Errorf("invalid duration format: must start with P")
	}
	durationStr = durationStr[1:]

	var totalDuration time.Duration

	// Parse weeks (W)
	if idx := strings.Index(durationStr, "W"); idx >= 0 {
		weeksPart := durationStr[:idx]
		if weeks, err := strconv.Atoi(weeksPart); err == nil {
			totalDuration += time.Duration(weeks) * 7 * 24 * time.Hour
		}
		durationStr = durationStr[idx+1:]
	}

	// Parse days (D)
	if idx := strings.Index(durationStr, "D"); idx >= 0 {
		daysPart := durationStr[:idx]
		if days, err := strconv.Atoi(daysPart); err == nil {
			totalDuration += time.Duration(days) * 24 * time.Hour
		}
		durationStr = durationStr[idx+1:]
	}

	// Parse time components (after T)
	if strings.HasPrefix(durationStr, "T") {
		durationStr = durationStr[1:]

		// Parse hours (H)
		if idx := strings.Index(durationStr, "H"); idx >= 0 {
			hoursPart := durationStr[:idx]
			if hours, err := strconv.Atoi(hoursPart); err == nil {
				totalDuration += time.Duration(hours) * time.Hour
			}
			durationStr = durationStr[idx+1:]
		}

		// Parse minutes (M)
		if idx := strings.Index(durationStr, "M"); idx >= 0 {
			minutesPart := durationStr[:idx]
			if minutes, err := strconv.Atoi(minutesPart); err == nil {
				totalDuration += time.Duration(minutes) * time.Minute
			}
			durationStr = durationStr[idx+1:]
		}

		// Parse seconds (S)
		if idx := strings.Index(durationStr, "S"); idx >= 0 {
			secondsPart := durationStr[:idx]
			if seconds, err := strconv.Atoi(secondsPart); err == nil {
				totalDuration += time.Duration(seconds) * time.Second
			}
		}
	}

	return time.Duration(sign) * totalDuration, nil
}

// ExistingDayContent represents parsed content from an existing daily markdown file
type ExistingDayContent struct {
	Title           string
	AllDayEvents    []string
	ScheduledEvents []string
	Tasks           []string
	OtherContent    []string // Any content that doesn't fit the standard sections
	Frontmatter     map[string]interface{} // Raw existing YAML frontmatter
	HasFrontmatter  bool                   // Whether the file had frontmatter
	CustomSections  map[string][]string    // Custom sections with their content
}

// parseExistingFile reads and parses an existing daily markdown file
func parseExistingFile(filename string) (*ExistingDayContent, error) {
	file, err := os.Open(filename)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil // File doesn't exist, return nil (not an error)
		}
		return nil, fmt.Errorf("failed to open existing file %s: %v", filename, err)
	}
	defer file.Close()

	content := &ExistingDayContent{
		CustomSections: make(map[string][]string),
	}
	scanner := bufio.NewScanner(file)

	currentSection := ""
	var currentItems []string
	inFrontmatter := false
	frontmatterComplete := false
	var frontmatterLines []string

	for scanner.Scan() {
		line := scanner.Text()

		// Handle YAML frontmatter
		if !frontmatterComplete {
			if line == "---" {
				if !inFrontmatter {
					// Starting frontmatter
					inFrontmatter = true
					content.HasFrontmatter = true
					continue
				} else {
					// Ending frontmatter
					frontmatterComplete = true
					// Parse the collected frontmatter
					if len(frontmatterLines) > 0 {
						frontmatterYAML := strings.Join(frontmatterLines, "\n")
						var fm map[string]interface{}
						if err := yaml.Unmarshal([]byte(frontmatterYAML), &fm); err == nil {
							content.Frontmatter = fm
						}
					}
					continue
				}
			}
			if inFrontmatter {
				frontmatterLines = append(frontmatterLines, line)
				continue
			}
			// If we reach here and haven't seen frontmatter delimiter,
			// then there's no frontmatter
			if line != "" && !strings.HasPrefix(line, "#") {
				frontmatterComplete = true
			}
		}

		// Check for title (date header)
		if strings.HasPrefix(line, "# ") {
			content.Title = line
			continue
		}

		// Check for section headers
		if strings.HasPrefix(line, "## ") {
			// Save previous section
			savePreviousSection(content, currentSection, currentItems)

			// Start new section
			switch line {
			case "## All Day Events":
				currentSection = "allday"
			case "## Scheduled Events":
				currentSection = "scheduled"
			case "## Tasks":
				currentSection = "tasks"
			default:
				// This is a custom section - store the header name
				currentSection = line
			}
			currentItems = []string{}
			continue
		}

		// Skip empty lines
		if strings.TrimSpace(line) == "" {
			continue
		}

		// Add line to current section
		if currentSection != "" {
			currentItems = append(currentItems, line)
		} else {
			// Content before any section headers (but after frontmatter)
			content.OtherContent = append(content.OtherContent, line)
		}
	}

	// Save the last section
	savePreviousSection(content, currentSection, currentItems)

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading file %s: %v", filename, err)
	}

	return content, nil
}

// savePreviousSection saves items to the appropriate section in ExistingDayContent
func savePreviousSection(content *ExistingDayContent, section string, items []string) {
	switch section {
	case "allday":
		content.AllDayEvents = items
	case "scheduled":
		content.ScheduledEvents = items
	case "tasks":
		content.Tasks = items
	default:
		if section != "" {
			if strings.HasPrefix(section, "##") {
				// This is a custom section header
				content.CustomSections[section] = items
			} else {
				// This is other content (before any headers)
				content.OtherContent = append(content.OtherContent, items...)
			}
		}
	}
}

// deduplicate removes duplicate items from a slice while preserving order
func deduplicate(items []string) []string {
	seen := make(map[string]bool)
	result := []string{}

	for _, item := range items {
		// Normalize the item for comparison (trim whitespace)
		normalized := strings.TrimSpace(item)
		if normalized == "" {
			continue
		}

		if !seen[normalized] {
			seen[normalized] = true
			result = append(result, item)
		}
	}

	return result
}

// smartDeduplicate compares items based on core content (without hashtags)
// and keeps the version with the most complete hashtag information
func smartDeduplicate(items []string) []string {
	// Map UIDs to the latest version, and core content to best version for non-UID items
	uidVersions := make(map[string]string)
	bestVersions := make(map[string]string)

	for _, item := range items {
		normalized := strings.TrimSpace(item)
		if normalized == "" {
			continue
		}

		// Extract UID if present
		uid := extractUID(normalized)
		if uid != "" {
			// For UID-based items, always keep the latest version (last one wins)
			uidVersions[uid] = normalized
		} else {
			// For non-UID items, use old logic (core content comparison)
			coreContent := extractCoreContent(normalized)
			if existing, exists := bestVersions[coreContent]; !exists || hasMoreCompleteHashtags(normalized, existing) {
				bestVersions[coreContent] = normalized
			}
		}
	}

	// Convert maps back to slice, preserving original order as much as possible
	result := []string{}
	seenUIDs := make(map[string]bool)
	seenContent := make(map[string]bool)

	for _, item := range items {
		normalized := strings.TrimSpace(item)
		if normalized == "" {
			continue
		}

		uid := extractUID(normalized)
		if uid != "" {
			// UID-based deduplication - use latest version
			if !seenUIDs[uid] {
				seenUIDs[uid] = true
				result = append(result, uidVersions[uid])
			}
		} else {
			// Content-based deduplication - use best version
			coreContent := extractCoreContent(normalized)
			bestVersion := bestVersions[coreContent]
			if !seenContent[bestVersion] {
				seenContent[bestVersion] = true
				result = append(result, bestVersion)
			}
		}
	}

	return result
}

// extractUID extracts the UID from an HTML comment in a markdown item
// Format: <!-- uid:some-uid-value -->
func extractUID(item string) string {
	uidPattern := regexp.MustCompile(`<!--\s*uid:([^-\s][^\s]*?)\s*-->`)
	matches := uidPattern.FindStringSubmatch(item)
	if len(matches) > 1 {
		return matches[1]
	}
	return ""
}

// extractCoreContent removes hashtags from the end of a markdown item to get core content
func extractCoreContent(item string) string {
	// Handle multi-line items by processing each line and removing hashtags
	lines := strings.Split(item, "\n")
	var cleanLines []string

	for _, line := range lines {
		// Pattern to match hashtags at the end: one or more #word patterns, possibly with trailing spaces
		hashtagPattern := regexp.MustCompile(`(\s+#[a-zA-Z0-9-]+)*\s*$`)
		cleanLine := strings.TrimSpace(hashtagPattern.ReplaceAllString(line, ""))
		if cleanLine != "" {
			// Normalize indentation - remove leading spaces to focus on content
			cleanLines = append(cleanLines, strings.TrimSpace(cleanLine))
		}
	}

	// Join lines back but normalize spacing for comparison
	result := strings.Join(cleanLines, "\n")
	// Also normalize multiple whitespace to single spaces within lines
	spacePattern := regexp.MustCompile(`\s+`)
	result = spacePattern.ReplaceAllString(result, " ")
	return strings.TrimSpace(result)
}

// hasMoreCompleteHashtags determines if the first item has more complete hashtag information than the second
func hasMoreCompleteHashtags(item1, item2 string) bool {
	hashtags1 := extractHashtags(item1)
	hashtags2 := extractHashtags(item2)

	// Prefer the item with more hashtags, or if equal, the one that's not empty
	if len(hashtags1) != len(hashtags2) {
		return len(hashtags1) > len(hashtags2)
	}

	// If same number of hashtags, prefer the one that comes later (likely newer)
	return len(hashtags1) > 0
}

// extractHashtags returns all hashtags found in an item
func extractHashtags(item string) []string {
	hashtagPattern := regexp.MustCompile(`#[a-zA-Z0-9-]+`)
	return hashtagPattern.FindAllString(item, -1)
}

// updateItemsWithNewHashtags updates existing markdown items to add new hashtags if enabled
func updateItemsWithNewHashtags(items []string, useHashtags, useCalendarTags bool, isEvent bool) []string {
	if !useHashtags && !useCalendarTags {
		return items // No hashtags to add
	}

	var updatedItems []string
	for _, item := range items {
		updatedItems = append(updatedItems, updateSingleItemWithHashtags(item, useHashtags, useCalendarTags, isEvent))
	}
	return updatedItems
}

// updateSingleItemWithHashtags updates a single markdown item to add missing hashtags
func updateSingleItemWithHashtags(item string, useHashtags, useCalendarTags bool, isEvent bool) string {
	if !useHashtags && !useCalendarTags {
		return item
	}

	// Pattern to match existing hashtags at the end of the line
	hashtagPattern := regexp.MustCompile(`(\s+#[a-zA-Z0-9-]+)*\s*$`)

	// Extract existing hashtags
	matches := hashtagPattern.FindAllString(item, -1)
	var existingHashtags []string
	for _, match := range matches {
		tags := strings.Fields(match)
		for _, tag := range tags {
			if strings.HasPrefix(tag, "#") {
				existingHashtags = append(existingHashtags, tag)
			}
		}
	}

	// Check if we need to add standard hashtags
	var newHashtags []string
	if useHashtags {
		expectedTag := "#event"
		if !isEvent {
			expectedTag = "#task"
		}

		hasStandardTag := false
		for _, tag := range existingHashtags {
			if tag == expectedTag {
				hasStandardTag = true
				break
			}
		}
		if !hasStandardTag {
			newHashtags = append(newHashtags, expectedTag)
		}
	}

	// Extract calendar name from item (between square brackets)
	var calendarTag string
	if useCalendarTags {
		calendarPattern := regexp.MustCompile(`\[([^\]]+)\]`)
		calendarMatches := calendarPattern.FindStringSubmatch(item)
		if len(calendarMatches) > 1 {
			calendarName := calendarMatches[1]
			sanitizedCalendarName := sanitizeForHashtag(calendarName)
			if sanitizedCalendarName != "" {
				calendarTag = "#" + sanitizedCalendarName

				// Check if calendar tag already exists
				hasCalendarTag := false
				for _, tag := range existingHashtags {
					if tag == calendarTag {
						hasCalendarTag = true
						break
					}
				}
				if !hasCalendarTag {
					newHashtags = append(newHashtags, calendarTag)
				}
			}
		}
	}

	// If no new hashtags to add, return original item
	if len(newHashtags) == 0 {
		return item
	}

	// Remove existing hashtags from the end and add all hashtags (existing + new)
	baseItem := hashtagPattern.ReplaceAllString(item, "")
	baseItem = strings.TrimSpace(baseItem)

	// Combine existing and new hashtags, then deduplicate
	allHashtags := append(existingHashtags, newHashtags...)
	allHashtags = deduplicateHashtags(allHashtags)
	if len(allHashtags) > 0 {
		return baseItem + " " + strings.Join(allHashtags, " ")
	}

	return baseItem
}

// isInvalidHashtag checks if a hashtag should be filtered out
func isInvalidHashtag(tag string) bool {
	// Filter out empty, whitespace-only, or very short meaningless tags
	tag = strings.TrimSpace(tag)
	if tag == "" {
		return true
	}

	// Filter out specific invalid hashtags
	invalidTags := []string{"-", "x", "_", ".", ",", ":", ";", "!", "?"}
	for _, invalid := range invalidTags {
		if tag == invalid {
			return true
		}
	}

	// Filter out single character tags that are not alphanumeric
	if len(tag) == 1 && !((tag[0] >= 'a' && tag[0] <= 'z') || (tag[0] >= '0' && tag[0] <= '9')) {
		return true
	}

	return false
}

// sanitizeForHashtag converts a calendar name to a clean hashtag format
func sanitizeForHashtag(calendarName string) string {
	// Generate a sanitized hashtag from calendar name
	calendarTag := strings.ToLower(calendarName)
	calendarTag = strings.ReplaceAll(calendarTag, " ", "-")
	calendarTag = strings.ReplaceAll(calendarTag, "_", "-")
	// Remove non-alphanumeric characters except hyphens
	var cleanTag strings.Builder
	for _, r := range calendarTag {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '-' {
			cleanTag.WriteRune(r)
		}
	}
	// Clean up multiple hyphens and trim
	result := cleanTag.String()
	// Replace multiple consecutive hyphens with single hyphen
	for strings.Contains(result, "--") {
		result = strings.ReplaceAll(result, "--", "-")
	}
	// Trim leading and trailing hyphens
	result = strings.Trim(result, "-")

	// Filter out invalid hashtags
	if isInvalidHashtag(result) {
		return ""
	}

	return result
}

// deduplicateHashtags removes duplicate hashtags from a slice while preserving order
func deduplicateHashtags(hashtags []string) []string {
	seen := make(map[string]bool)
	var result []string

	for _, hashtag := range hashtags {
		hashtag = strings.TrimSpace(hashtag)

		// Skip empty hashtags and invalid hashtags
		if hashtag == "" {
			continue
		}

		// Remove # prefix if present for validation, then add it back
		cleanTag := hashtag
		if strings.HasPrefix(hashtag, "#") {
			cleanTag = hashtag[1:]
		}

		// Skip invalid hashtags
		if isInvalidHashtag(cleanTag) {
			continue
		}

		// Ensure hashtag has # prefix
		if !strings.HasPrefix(hashtag, "#") {
			hashtag = "#" + hashtag
		}

		if !seen[hashtag] {
			seen[hashtag] = true
			result = append(result, hashtag)
		}
	}

	return result
}

// ExistingTodoContent represents parsed content from an existing todo.md file
type ExistingTodoContent struct {
	Title        string
	Tasks        []string
	OtherContent []string                // Any content that doesn't fit the standard sections
	Frontmatter  map[string]interface{}  // Raw existing YAML frontmatter
	HasFrontmatter bool                  // Whether the file had frontmatter
	CustomSections map[string][]string   // Custom sections with their content
}

// parseExistingTodoFile reads and parses an existing todo.md file
func parseExistingTodoFile(filename string) (*ExistingTodoContent, error) {
	file, err := os.Open(filename)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil // File doesn't exist, return nil (not an error)
		}
		return nil, fmt.Errorf("failed to open existing todo.md file %s: %v", filename, err)
	}
	defer file.Close()

	content := &ExistingTodoContent{
		CustomSections: make(map[string][]string),
	}
	scanner := bufio.NewScanner(file)

	currentSection := ""
	var currentItems []string
	inFrontmatter := false
	frontmatterComplete := false
	var frontmatterLines []string

	for scanner.Scan() {
		line := scanner.Text()

		// Handle YAML frontmatter
		if !frontmatterComplete {
			if line == "---" {
				if !inFrontmatter {
					// Starting frontmatter
					inFrontmatter = true
					content.HasFrontmatter = true
					continue
				} else {
					// Ending frontmatter
					frontmatterComplete = true
					// Parse the collected frontmatter
					if len(frontmatterLines) > 0 {
						frontmatterYAML := strings.Join(frontmatterLines, "\n")
						var fm map[string]interface{}
						if err := yaml.Unmarshal([]byte(frontmatterYAML), &fm); err == nil {
							content.Frontmatter = fm
						}
					}
					continue
				}
			}
			if inFrontmatter {
				frontmatterLines = append(frontmatterLines, line)
				continue
			}
			// If we reach here and haven't seen frontmatter delimiter,
			// then there's no frontmatter
			if line != "" && !strings.HasPrefix(line, "#") {
				frontmatterComplete = true
			}
		}

		// Check for title (main header)
		if strings.HasPrefix(line, "# ") {
			content.Title = line
			continue
		}

		// Check for section headers
		if strings.HasPrefix(line, "## ") {
			// Save previous section
			savePreviousTodoSection(content, currentSection, currentItems)

			// Start new section
			if line == "## Tasks" || line == "## Todo" {
				currentSection = "tasks"
			} else {
				// This is a custom section - store the header name
				currentSection = line
			}
			currentItems = []string{}
			continue
		}

		// Skip empty lines
		if strings.TrimSpace(line) == "" {
			continue
		}

		// Add line to current section
		if currentSection != "" {
			currentItems = append(currentItems, line)
		} else {
			// Content before any section headers (but after frontmatter)
			content.OtherContent = append(content.OtherContent, line)
		}
	}

	// Save the last section
	savePreviousTodoSection(content, currentSection, currentItems)

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("error reading todo.md file %s: %v", filename, err)
	}

	return content, nil
}

// savePreviousTodoSection saves items to the appropriate section in ExistingTodoContent
func savePreviousTodoSection(content *ExistingTodoContent, section string, items []string) {
	switch section {
	case "tasks":
		content.Tasks = items
	default:
		if section != "" {
			if strings.HasPrefix(section, "##") {
				// This is a custom section header
				content.CustomSections[section] = items
			} else {
				// This is other content (before any headers)
				content.OtherContent = append(content.OtherContent, items...)
			}
		}
	}
}

// generateMergedTodoContent creates the final todo.md content by merging existing and new items
func generateMergedTodoContent(existingContent *ExistingTodoContent, newTasks []string, tasks []TodoMarkdown, useFrontmatter, useHashtags, useCalendarTags bool) string {
	var sb strings.Builder

	// Handle frontmatter - merge existing with new if requested
	if useFrontmatter || (existingContent != nil && existingContent.HasFrontmatter) {
		var mergedFrontmatter map[string]interface{}

		// Start with existing frontmatter if available
		if existingContent != nil && existingContent.Frontmatter != nil {
			mergedFrontmatter = make(map[string]interface{})
			// Copy existing frontmatter
			for k, v := range existingContent.Frontmatter {
				mergedFrontmatter[k] = v
			}
		} else {
			mergedFrontmatter = make(map[string]interface{})
		}

		// Update calendar-specific fields while preserving existing custom fields
		if existingTitle, titleExists := mergedFrontmatter["title"]; !titleExists || isGeneratedTitle(existingTitle) {
			mergedFrontmatter["title"] = "Todo List"
		}

		// Update task statistics
		mergedFrontmatter["task_count"] = len(newTasks)
		mergedFrontmatter["type"] = "todo"

		// Collect unique tags from existing and new tasks
		tagSet := make(map[string]bool)

		// Preserve existing tags (handle both []interface{} and []string formats)
		if existingTags, exists := mergedFrontmatter["tags"]; exists {
			switch tags := existingTags.(type) {
			case []interface{}:
				for _, tag := range tags {
					if tagStr, ok := tag.(string); ok && tagStr != "" {
						tagSet[tagStr] = true
					}
				}
			case []string:
				for _, tag := range tags {
					if tag != "" {
						tagSet[tag] = true
					}
				}
			case string:
				// Handle single tag as string
				if tags != "" {
					tagSet[tags] = true
				}
			}
		}

		// Add new tags from tasks
		for _, task := range tasks {
			for _, cat := range task.Categories {
				if cat != "" {
					tagSet[cat] = true
				}
			}
		}

		var tagsList []string
		for tag := range tagSet {
			tagsList = append(tagsList, tag)
		}
		// Only set tags field if there are actual tags
		if len(tagsList) > 0 {
			mergedFrontmatter["tags"] = tagsList
		}

		// Generate YAML frontmatter
		yamlData, err := yaml.Marshal(mergedFrontmatter)
		if err == nil {
			sb.WriteString(fmt.Sprintf("---\n%s---\n\n", string(yamlData)))
		}
	}

	// Generate title
	if existingContent != nil && existingContent.Title != "" {
		sb.WriteString(existingContent.Title)
		sb.WriteString("\n\n")
	} else {
		sb.WriteString("# Todo\n\n")
	}

	// Add other content from existing file (if any)
	if existingContent != nil && len(existingContent.OtherContent) > 0 {
		for _, line := range existingContent.OtherContent {
			sb.WriteString(line)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Add custom sections from existing file (if any)
	if existingContent != nil {
		for sectionHeader, sectionItems := range existingContent.CustomSections {
			// Skip standard sections as they'll be handled below
			if sectionHeader == "## Tasks" || sectionHeader == "## Todo" {
				continue
			}

			if len(sectionItems) > 0 {
				sb.WriteString(sectionHeader)
				sb.WriteString("\n\n")
				for _, item := range sectionItems {
					sb.WriteString(item)
					sb.WriteString("\n")
				}
				sb.WriteString("\n")
			}
		}
	}

	// Merge and deduplicate tasks
	var taskItems []string
	if existingContent != nil {
		taskItems = append(taskItems, existingContent.Tasks...)
	}
	taskItems = append(taskItems, newTasks...)
	taskItems = smartDeduplicate(taskItems)

	// Update existing tasks with new hashtags if needed
	if existingContent != nil {
		taskItems = updateItemsWithNewHashtags(taskItems, useHashtags, useCalendarTags, false)
	}

	// Add tasks section
	if len(taskItems) > 0 {
		sb.WriteString("## Tasks\n\n")
		for _, item := range taskItems {
			sb.WriteString(item)
			sb.WriteString("\n")
		}
	}

	return sb.String()
}

// generateFrontmatter creates YAML frontmatter for a daily file
func generateFrontmatter(date string, allDayCount, scheduledCount, taskCount int, events []EventMarkdown, tasks []TodoMarkdown, useFrontmatter bool) string {
	if !useFrontmatter {
		return ""
	}

	var title string
	if date == "0001-01-01" {
		title = "Events (Date TBD)"
	} else {
		if parsedDate, err := time.Parse("2006-01-02", date); err == nil {
			title = parsedDate.Format("Monday, January 2, 2006")
		} else {
			title = date
		}
	}

	// Collect unique tags from events and tasks
	tagSet := make(map[string]bool)
	for _, event := range events {
		for _, cat := range event.Categories {
			if cat != "" {
				tagSet[cat] = true
			}
		}
	}
	for _, task := range tasks {
		for _, cat := range task.Categories {
			if cat != "" {
				tagSet[cat] = true
			}
		}
	}

	var tags []string
	for tag := range tagSet {
		tags = append(tags, tag)
	}

	frontmatter := DayFrontmatter{
		Date:        date,
		Title:       title,
		EventCount:  allDayCount + scheduledCount,
		TaskCount:   taskCount,
		AllDayCount: allDayCount,
		Tags:        tags,
		Type:        "daily",
	}

	yamlData, err := yaml.Marshal(frontmatter)
	if err != nil {
		return ""
	}

	return fmt.Sprintf("---\n%s---\n\n", string(yamlData))
}

// generateMergedContent creates the final markdown content by merging existing and new items
func generateMergedContent(date string, existingContent *ExistingDayContent, newAllDay, newScheduled, newTasks []string) string {
	return generateMergedContentWithFrontmatter(date, existingContent, newAllDay, newScheduled, newTasks, nil, nil, false, false, false)
}

// generateMergedContentWithFrontmatter creates the final markdown content with optional frontmatter
func generateMergedContentWithFrontmatter(date string, existingContent *ExistingDayContent, newAllDay, newScheduled, newTasks []string, events []EventMarkdown, tasks []TodoMarkdown, useFrontmatter, useHashtags, useCalendarTags bool) string {
	var sb strings.Builder

	// Handle frontmatter - merge existing with new if requested
	if useFrontmatter || (existingContent != nil && existingContent.HasFrontmatter) {
		var mergedFrontmatter map[string]interface{}

		// Start with existing frontmatter if available
		if existingContent != nil && existingContent.Frontmatter != nil {
			mergedFrontmatter = make(map[string]interface{})
			// Copy existing frontmatter
			for k, v := range existingContent.Frontmatter {
				mergedFrontmatter[k] = v
			}
		} else {
			mergedFrontmatter = make(map[string]interface{})
		}

		// Update calendar-specific fields while preserving existing custom fields
		mergedFrontmatter["date"] = date

		// Only update title if it doesn't exist or if it's a generated calendar title
		if existingTitle, titleExists := mergedFrontmatter["title"]; !titleExists || isGeneratedTitle(existingTitle) {
			if date == "0001-01-01" {
				mergedFrontmatter["title"] = "Events (Date TBD)"
			} else {
				if parsedDate, err := time.Parse("2006-01-02", date); err == nil {
					mergedFrontmatter["title"] = parsedDate.Format("Monday, January 2, 2006")
				} else {
					mergedFrontmatter["title"] = date
				}
			}
		}

		// Update calendar stats
		mergedFrontmatter["event_count"] = len(newAllDay) + len(newScheduled)
		mergedFrontmatter["task_count"] = len(newTasks)
		mergedFrontmatter["allday_count"] = len(newAllDay)

		// Only set type if it doesn't exist or enhance existing type
		if existingType, typeExists := mergedFrontmatter["type"]; !typeExists {
			mergedFrontmatter["type"] = "daily"
		} else if typeStr, ok := existingType.(string); ok && typeStr != "daily" {
			// Preserve custom types but add daily as secondary type if needed
			if !strings.Contains(typeStr, "daily") {
				mergedFrontmatter["type"] = fmt.Sprintf("%s, daily", typeStr)
			}
		}

		// Collect unique tags from existing and new events/tasks
		tagSet := make(map[string]bool)

		// Preserve existing tags (handle both []interface{} and []string formats)
		if existingTags, exists := mergedFrontmatter["tags"]; exists {
			switch tags := existingTags.(type) {
			case []interface{}:
				for _, tag := range tags {
					if tagStr, ok := tag.(string); ok && tagStr != "" {
						tagSet[tagStr] = true
					}
				}
			case []string:
				for _, tag := range tags {
					if tag != "" {
						tagSet[tag] = true
					}
				}
			case string:
				// Handle single tag as string
				if tags != "" {
					tagSet[tags] = true
				}
			}
		}

		// Add new tags from events and tasks
		for _, event := range events {
			for _, cat := range event.Categories {
				if cat != "" {
					tagSet[cat] = true
				}
			}
		}
		for _, task := range tasks {
			for _, cat := range task.Categories {
				if cat != "" {
					tagSet[cat] = true
				}
			}
		}

		var tags []string
		for tag := range tagSet {
			tags = append(tags, tag)
		}
		// Only set tags field if there are actual tags
		if len(tags) > 0 {
			mergedFrontmatter["tags"] = tags
		}

		// Generate YAML frontmatter
		yamlData, err := yaml.Marshal(mergedFrontmatter)
		if err == nil {
			sb.WriteString(fmt.Sprintf("---\n%s---\n\n", string(yamlData)))
		}
	}

	// Generate title
	if date == "0001-01-01" {
		sb.WriteString("# Events (Date TBD)\n\n")
	} else {
		parsedDate, _ := time.Parse("2006-01-02", date)
		sb.WriteString(fmt.Sprintf("# %s\n\n", parsedDate.Format("Monday, January 2, 2006")))
	}

	// Merge and deduplicate all-day events
	var allDayItems []string
	if existingContent != nil {
		allDayItems = append(allDayItems, existingContent.AllDayEvents...)
	}
	allDayItems = append(allDayItems, newAllDay...)
	allDayItems = smartDeduplicate(allDayItems)

	// Merge and deduplicate scheduled events
	var scheduledItems []string
	if existingContent != nil {
		scheduledItems = append(scheduledItems, existingContent.ScheduledEvents...)
	}
	scheduledItems = append(scheduledItems, newScheduled...)
	scheduledItems = smartDeduplicate(scheduledItems)

	// Merge and deduplicate tasks
	var taskItems []string
	if existingContent != nil {
		taskItems = append(taskItems, existingContent.Tasks...)
	}
	taskItems = append(taskItems, newTasks...)
	taskItems = smartDeduplicate(taskItems)

	// Update existing items with new hashtags if needed
	if existingContent != nil {
		allDayItems = updateItemsWithNewHashtags(allDayItems, useHashtags, useCalendarTags, true)
		scheduledItems = updateItemsWithNewHashtags(scheduledItems, useHashtags, useCalendarTags, true)
		taskItems = updateItemsWithNewHashtags(taskItems, useHashtags, useCalendarTags, false)
	}

	// Add other content from existing file (if any)
	if existingContent != nil && len(existingContent.OtherContent) > 0 {
		for _, line := range existingContent.OtherContent {
			sb.WriteString(line)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Add custom sections from existing file (if any)
	if existingContent != nil {
		for sectionHeader, sectionItems := range existingContent.CustomSections {
			// Skip standard sections as they'll be handled below
			if sectionHeader == "## All Day Events" || sectionHeader == "## Scheduled Events" || sectionHeader == "## Tasks" {
				continue
			}

			if len(sectionItems) > 0 {
				sb.WriteString(sectionHeader)
				sb.WriteString("\n\n")
				for _, item := range sectionItems {
					sb.WriteString(item)
					sb.WriteString("\n")
				}
				sb.WriteString("\n")
			}
		}
	}

	// Add all-day events section
	if len(allDayItems) > 0 {
		sb.WriteString("## All Day Events\n\n")
		for _, item := range allDayItems {
			sb.WriteString(item)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Add scheduled events section
	if len(scheduledItems) > 0 {
		sb.WriteString("## Scheduled Events\n\n")
		for _, item := range scheduledItems {
			sb.WriteString(item)
			sb.WriteString("\n")
		}
		sb.WriteString("\n")
	}

	// Add tasks section
	if len(taskItems) > 0 {
		sb.WriteString("## Tasks\n\n")
		for _, item := range taskItems {
			sb.WriteString(item)
			sb.WriteString("\n")
		}
	}

	return sb.String()
}

// formatDuration formats a duration in a human-readable way
func formatDuration(d time.Duration) string {
	if d < 0 {
		return "0m"
	}

	hours := int(d.Hours())
	minutes := int(d.Minutes()) % 60

	if hours == 0 {
		return fmt.Sprintf("%dm", minutes)
	} else if minutes == 0 {
		return fmt.Sprintf("%dh", hours)
	} else {
		return fmt.Sprintf("%dh %dm", hours, minutes)
	}
}

// ProgressCallback is a function type for reporting progress during file generation
type ProgressCallback func(message string, current, total int)

// DayFrontmatter represents the YAML frontmatter for daily files
type DayFrontmatter struct {
	Date        string   `yaml:"date"`
	Title       string   `yaml:"title"`
	EventCount  int      `yaml:"event_count"`
	TaskCount   int      `yaml:"task_count"`
	AllDayCount int      `yaml:"allday_count"`
	Tags        []string `yaml:"tags,omitempty"`
	Type        string   `yaml:"type"`
}

// EventFrontmatter represents event-specific frontmatter data
type EventFrontmatter struct {
	Title      string    `yaml:"title"`
	StartTime  time.Time `yaml:"start_time,omitempty"`
	EndTime    time.Time `yaml:"end_time,omitempty"`
	AllDay     bool      `yaml:"all_day"`
	Location   string    `yaml:"location,omitempty"`
	UID        string    `yaml:"uid,omitempty"`
	Status     string    `yaml:"status,omitempty"`
	Categories []string  `yaml:"categories,omitempty"`
	Type       string    `yaml:"type"`
}

// TaskFrontmatter represents task-specific frontmatter data
type TaskFrontmatter struct {
	Title      string    `yaml:"title"`
	Status     string    `yaml:"status,omitempty"`
	Priority   string    `yaml:"priority,omitempty"`
	DueDate    time.Time `yaml:"due_date,omitempty"`
	Completed  bool      `yaml:"completed"`
	UID        string    `yaml:"uid,omitempty"`
	Categories []string  `yaml:"categories,omitempty"`
	Type       string    `yaml:"type"`
}

// GenerateDailyFilesWithTasks groups events and tasks by date and creates daily markdown files
func GenerateDailyFilesWithTasks(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags bool) error {
	return GenerateDailyFilesWithTasksAndProgress(outputDir, events, tasks, useDueDateEmoji, useHashtags, nil)
}

// GenerateDailyFilesWithTasksAndOptions groups events and tasks by date and creates daily markdown files with full options
func GenerateDailyFilesWithTasksAndOptions(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions bool) error {
	return GenerateDailyFilesWithTasksProgressAndFrontmatterAndDescriptions(outputDir, events, tasks, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, nil)
}

// GenerateDailyFilesWithCompleteOptions groups events and tasks by date and creates daily markdown files with all available options
func GenerateDailyFilesWithCompleteOptions(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, eventCheckboxes bool) error {
	return GenerateDailyFilesWithAllOptions(outputDir, events, tasks, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, eventCheckboxes, false, false, nil)
}

// GenerateDailyFilesWithTasksAndFrontmatter groups events and tasks by date and creates daily markdown files with frontmatter
func GenerateDailyFilesWithTasksAndFrontmatter(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter bool) error {
	return GenerateDailyFilesWithTasksProgressAndFrontmatter(outputDir, events, tasks, useDueDateEmoji, useHashtags, useFrontmatter, nil)
}

// GenerateDailyFilesWithTasksAndProgress groups events and tasks by date and creates daily markdown files with progress reporting
func GenerateDailyFilesWithTasksAndProgress(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags bool, progressCallback ProgressCallback) error {
	return GenerateDailyFilesWithTasksProgressAndFrontmatter(outputDir, events, tasks, useDueDateEmoji, useHashtags, false, progressCallback)
}

// GenerateDailyFilesWithTasksProgressAndFrontmatter groups events and tasks by date and creates daily markdown files with progress reporting and frontmatter support
func GenerateDailyFilesWithTasksProgressAndFrontmatter(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter bool, progressCallback ProgressCallback) error {
	return GenerateDailyFilesWithTasksProgressAndFrontmatterAndDescriptions(outputDir, events, tasks, useDueDateEmoji, useHashtags, useFrontmatter, false, progressCallback)
}

// GenerateDailyFilesWithTasksProgressAndFrontmatterAndDescriptions groups events and tasks by date and creates daily markdown files with full options
func GenerateDailyFilesWithTasksProgressAndFrontmatterAndDescriptions(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions bool, progressCallback ProgressCallback) error {
	return GenerateDailyFilesWithAllOptions(outputDir, events, tasks, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, false, false, false, progressCallback)
}

// GenerateDailyFilesWithAllOptions groups events and tasks by date and creates daily markdown files with complete control over formatting
func GenerateDailyFilesWithAllOptions(outputDir string, events []EventMarkdown, tasks []TodoMarkdown, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, eventCheckboxes, useCalendarTags, useObsidianEmojis bool, progressCallback ProgressCallback) error {
	// Group events by date
	eventsByDate := make(map[string][]EventMarkdown)
	tasksByDate := make(map[string][]TodoMarkdown)
	var noDueDateTasks []TodoMarkdown

	for _, event := range events {
		var dateKey string
		if event.StartTime.IsZero() {
			dateKey = "0001-01-01"
		} else {
			dateKey = event.StartTime.Format("2006-01-02")
		}
		eventsByDate[dateKey] = append(eventsByDate[dateKey], event)
	}

	// Group tasks by due date, separating those without due dates
	for _, task := range tasks {
		if task.DueDate.IsZero() {
			noDueDateTasks = append(noDueDateTasks, task)
		} else {
			dateKey := task.DueDate.Format("2006-01-02")
			tasksByDate[dateKey] = append(tasksByDate[dateKey], task)
		}
	}

	// Get all unique dates from both events and tasks
	allDates := make(map[string]bool)
	for date := range eventsByDate {
		allDates[date] = true
	}
	for date := range tasksByDate {
		allDates[date] = true
	}

	// Convert to slice for indexed iteration
	datesList := make([]string, 0, len(allDates))
	for date := range allDates {
		datesList = append(datesList, date)
	}

	if progressCallback != nil {
		progressCallback(fmt.Sprintf("Generating %d daily files", len(datesList)), 0, len(datesList))
	}

	// Create a file for each date
	for i, date := range datesList {
		if progressCallback != nil {
			if date == "0001-01-01" {
				progressCallback("Processing items with no date", i+1, len(datesList))
			} else {
				progressCallback(fmt.Sprintf("Processing %s", date), i+1, len(datesList))
			}
		}
		dayEvents := eventsByDate[date]
		dayTasks := tasksByDate[date]
		// Sort events by start time
		var allDayEvents, timedEvents []EventMarkdown
		for _, event := range dayEvents {
			if event.AllDay || event.StartTime.IsZero() {
				allDayEvents = append(allDayEvents, event)
			} else {
				timedEvents = append(timedEvents, event)
			}
		}

		// Simple sort by start time for timed events
		for i := 0; i < len(timedEvents)-1; i++ {
			for j := i + 1; j < len(timedEvents); j++ {
				if timedEvents[i].StartTime.After(timedEvents[j].StartTime) {
					timedEvents[i], timedEvents[j] = timedEvents[j], timedEvents[i]
				}
			}
		}

		// Collect new content as strings for merging
		var newAllDayEvents, newScheduledEvents, newTasks []string

		for _, event := range allDayEvents {
			newAllDayEvents = append(newAllDayEvents, strings.TrimSpace(event.ToListItemWithAllOptions(useHashtags, ignoreDescriptions, eventCheckboxes, useCalendarTags, useObsidianEmojis)))
		}

		for _, event := range timedEvents {
			newScheduledEvents = append(newScheduledEvents, strings.TrimSpace(event.ToListItemWithAllOptions(useHashtags, ignoreDescriptions, eventCheckboxes, useCalendarTags, useObsidianEmojis)))
		}

		for _, task := range dayTasks {
			newTasks = append(newTasks, strings.TrimSpace(task.ToMarkdownWithOptionsAndCalendarTags(useDueDateEmoji, useHashtags, ignoreDescriptions, useCalendarTags)))
		}

		// Create directory structure
		var dirPath, filename string
		if date == "0001-01-01" {
			dirPath = filepath.Join(outputDir, "0001", "01")
		} else {
			parsedDate, _ := time.Parse("2006-01-02", date)
			dirPath = filepath.Join(outputDir, parsedDate.Format("2006"), parsedDate.Format("01"))
		}

		if err := os.MkdirAll(dirPath, 0755); err != nil {
			return fmt.Errorf("failed to create directory %s: %v", dirPath, err)
		}

		filename = filepath.Join(dirPath, fmt.Sprintf("%s.md", date))

		// Parse existing file if it exists
		existingContent, err := parseExistingFile(filename)
		if err != nil {
			return fmt.Errorf("failed to parse existing file %s: %v", filename, err)
		}

		// Report if we found existing content to merge
		if progressCallback != nil && existingContent != nil {
			existingItems := len(existingContent.AllDayEvents) + len(existingContent.ScheduledEvents) + len(existingContent.Tasks)
			if existingItems > 0 {
				progressCallback(fmt.Sprintf("Merging with %d existing items", existingItems), i+1, len(datesList))
			}
		}

		// Generate merged content
		mergedContent := generateMergedContentWithFrontmatter(date, existingContent, newAllDayEvents, newScheduledEvents, newTasks, dayEvents, dayTasks, useFrontmatter, useHashtags, useCalendarTags)

		// Write merged content to file
		file, err := os.Create(filename)
		if err != nil {
			return fmt.Errorf("failed to create file %s: %v", filename, err)
		}
		defer file.Close()

		if _, err := file.WriteString(mergedContent); err != nil {
			return fmt.Errorf("failed to write content to %s: %v", filename, err)
		}
	}

	// Generate todo.md file for tasks without due dates
	if len(noDueDateTasks) > 0 {
		if err := GenerateTodoFile(outputDir, noDueDateTasks, useDueDateEmoji, useHashtags, useFrontmatter, ignoreDescriptions, useCalendarTags, progressCallback); err != nil {
			return fmt.Errorf("failed to generate todo.md file: %v", err)
		}
	}

	return nil
}

// GenerateDailyFiles groups events by date and creates daily markdown files (backward compatibility)
func GenerateDailyFiles(outputDir string, events []EventMarkdown) error {
	return GenerateDailyFilesWithTasks(outputDir, events, nil, false, false)
}